exclude: '^tests/appl.patch$'

fail_fast: false
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
        exclude: "docs"
    -   id: end-of-file-fixer
        exclude: "docs"
    -   id: trailing-whitespace
        exclude: "docs"

-   repo: https://github.com/psf/black
    rev: 23.10.0
    hooks:
    -   id: black
        args: [ '--config', 'pyproject.toml' ]
        verbose: true
